Repository matter-labs/anvil-zksync, pull requests merged in 2023-09, with the labels that each got.

#95 fix: resolves #90 | fixes release executable and headers issue
  .github/workflows/release.yml
  Cargo.toml
  Cross.toml
Labels: needs review 👓

#101 feat: implement hardhat_setNonce
  SUPPORTED_APIS.md
  src/hardhat.rs
  test_endpoints.http
Labels: approved ✅

#104 feat: impl `eth_syncing`
  SUPPORTED_APIS.md
  src/node.rs
  test_endpoints.http
Labels: approved ✅

#93 feat: Implement evm_increaseTime and evm_setNextBlockTimestamp
  SUPPORTED_APIS.md
  src/evm.rs
  src/main.rs
  test_endpoints.http
Labels: needs review 👓

#100 chore: update lib.rs to include main rust docs content
  src/lib.rs
  src/main.rs
Labels: needs review 👓

#107 chore: add index.html to docs
  .github/workflows/docs.yaml
  src/deps/mod.rs
Labels: needs review 👓

#103 feat: Add simplelog
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  src/console_log.rs
  src/fork.rs
  src/formatter.rs
  src/main.rs
  src/node.rs
  src/zks.rs
Labels: needs changes 🔧

#102 feat: Implement eth_getBlockByHash and eth_getBlockByNumber with correct behavior
  Cargo.lock
  Cargo.toml
  SUPPORTED_APIS.md
  src/fork.rs
  src/http_fork_source.rs
  src/lib.rs
  src/main.rs
  src/node.rs
  src/testing.rs
  test_endpoints.http
Labels: needs review 👓

#121 feat: add eth_feeHistory
  SUPPORTED_APIS.md
  src/node.rs
  test_endpoints.http
Labels: approved ✅
